### ISSUE TITLE
Use decorators instead of function names

### ISSUE THREAD

**Issue by eric-wieser** [amoffat/focus#1]
MIght be beneficial to use decorators instead of `domain_www_somedomain_com` to indicate functions to run. Eg:

``` python
@domainfilter(".*.somedomain.com")
def afunctionnameinolongercareabout(dt, regexmatches):
    return False
```

Where `domainfilter` is a trivial decorator that adds to a global dictionary of regex/function pairs.

**Comment by amoffat** [comment]
It's a good idea.  I had considered this, but there is the problem of how to include the decorators in the blacklist file.  If the decorator definition wasn't embedded directly into the focus_blacklist.py, it would need to be imported from somewhere obvious.  It makes the learning curve a little steeper for writing rules.

One thing I should probably document better is that this:

``` python
def domain_somedomain_com(dt): return True
```

would match *.somedomain.com.  You can write more specific subdomain functions to whitelist/blacklist specific subdomains, and then have a catch-all function for the entire domain.  The way I had figured it, regexes would be mainly for matching subdomains, so doing this would eliminate the need for 99% of the regexes.

**Comment by eric-wieser** [comment]
Can't you just run the blacklist code in the scope of the main program? I'm not too experienced with execfile, but wouldn't this work?

``` python
#Define the decorator
allRules = {}
def domainfilter(regex):
    def decorator(f):
        allRules[regex] = f
        return f

def loadConfig():
    allRules.clear()
    execfile('focus_blacklist.py', {"domainfilter": domainfilter})
```

**Comment by amoffat** [comment]
Yeah that would.  I still think that the learning curve cost / benefit ratio of adding it is high though, since the current implementation handles most of what regexes would be used for.  I'll leave this issue open though and see if anyone else wants to weigh in.

**Comment by eric-wieser** [comment]
Perhaps have two decorators? I agree that forcing users to use regex isn't the right way to go. A solution would be to have one decorator for your current behaviour:

``` python
@focus.filter("facebook.com")
def stopMeFacebooking(dt):
    return 12 >= dt.hour >= 14
```

And then something like one of these for regex behaviour:

``` python
@focus.filter.regex(r".*\.co.uk")
def ignoreEngland(dt, groups):
    return dt.hour % 2 == 0
```

``` python
@focus.filter(regex = r".*\.co.uk")
def ignoreEngland(dt, groups):
    return dt.hour % 2 == 0
```

``` python
@focus.regexFilter(r".*\.co.uk")
def ignoreEngland(dt, groups):
    return dt.hour % 2 == 0
```

**Comment by amoffat** [comment]
As it stands, I'll have to vote no.  Regexes aren't necessary in the current scheme (for most of the uses), so the regex decorators are out.  That leaves the regular `focus.filter` decorator, which, to me, seems to be just another step that doesn't gain much.  The gains of the decorator is that it allows for arbitrary domain names easily...domains with weird characters, etc, that would have to be filtered out of a function name.  The drawbacks are that it's another piece for users to learn and it's another line to write that feels redundant.
