### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by nvartolomei** [amoffat/focus#12]
HTTPS request are not caught.

**Comment by amoffat** [comment]
Hi Nicolae,

I verified that both http://facebook.com and https://facebook.com is blocked with the default rules included with focus.  An HTTP/HTTPS request happens completely separate from a DNS lookup.  The order of events is something like this:
1. You type in https://facebook.com
2. The browser realizes it needs to resolve the ip for "facebook.com"
3. The browser gets the ip for "facebook.com" (notice, neither http nor https is a part of this step)
4. The browser makes an https request to the ip it resolved

What may be happening in your situation is your browser may have cached the ip of the website before you added the blocking rule.  If you give the browser a few minutes to flush out that old ip, you'll probably see the desired behavior.

To help more though, could you also tell me the site you wish to see blocked and paste your firewall rules?

**Comment by nvartolomei** [comment]
The strange thing was http://facebook.com/ was blocked and https://facebook.com/ not.

Cleared internal dns cache in Chrome there: `chrome://net-internals/#dns` and now works as expected.

Thanks for detailed answer and for **focus** ^_^

**Comment by amoffat** [comment]
No problem!  Take care Nicolae
