### ISSUE TITLE
Navigation Scrolling

### ISSUE THREAD

**Issue by mattgraham** [amoffat/focus#7]
@amoffat I've noticed that the navigation on your pages theme http://amoffat.github.com/focus/ doesn't scroll on the newest webkit update. This was a bug that happened after webkit updated recently. You can regenerate your page in the theme generator and it should fix it up without loosing anything. 

Let me know if you have any questions. Great work!

**Comment by amoffat** [comment]
@mattgraham awesome, thanks for the heads up!  and great theme!
